version: '3'

#volumes:
#  apps_volume:
#  logs_volume:
#  conf_volume:

services:
  web:
    image: bitsalt/devworks:latest
    volumes:
      - ./apps:/var/www
      - ./services/apache/sites-available:/etc/apache2/sites-available
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php
      - mariadb

  php:
    image: php:7.4.21-fpm-alpine3.13
    volumes:
      - ./apps:/var/www
    depends_on:
      - mariadb
    

  mariadb:
    image: mariadb:10.5
    volumes:
      - ./services/mariadb/data:/var/lib/mysql
    environment:
      TZ: "America/New_York"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "badRootPasswd"
      #      MYSQL_DATABASE: "devsite"
      #      MYSQL_USER: "devsite_usr"
      #      MYSQL_PASSWORD: "devsite_passwd"
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mariadb
