version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - 80:80
      - 443:443
    links:
      - php
    volumes:
    - ./app:/var/www/html
    - ./services/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - devworks-net

  php:
    image: bitsalt/local-php
    container_name: php-container
    expose:
      - 9000
    links:
      - mysql
    volumes:
      - ./app:/var/www/html
    networks:
      - devworks-net

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    volumes:
      - ./services/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    networks:
      - devworks-net

networks:
  devworks-net:
    driver: bridge

